# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-15 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20190415_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='title',
            new_name='title_name',
        ),
    ]
