# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-15 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0003_auto_20190415_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='title_name',
            new_name='title',
        ),
    ]
